language: node_js
cache:
  directories:
    # https://twitter.com/maybekatz/status/905213355748720640
    - ~/.npm

node_js:
  # https://medium.com/@mikeal/stop-supporting-old-releases-70cfa0e04b0c
  - "lts/*"

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master

before_install:
  - npm install -g npm
  - npm install

before_script:
  - npm prune

script:
  - npx sync-glitch-cli

notifications:
  email:
    on_failure: always

env:
  - GH_REPO="KimSunWook/working-hours-trello" GLITCH_TOKEN="3d1b369e-ca70-4a84-8f3c-85a6dca43ae5" GLITCH_PROJECT_ID="20a43737-dbbc-4409-a679-a1084acdccdb"
